name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Re-build
      run: make re

    - name: Clean files
      run: make clean

    - name: Clean files and executable
      run: make fclean
